version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: docker-node-tut
    restart: always
    ports:
      - 4026:8080
    command: bash /usr/src/app/start.sh
    env_file: .env
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPW
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
